sudo: false
language: java
os:
  - linux
#  - osx
jdk:
  - openjdk7
  - openjdk8
  - oraclejdk8
  - oraclejdk9

install:
  - wget "http://www.antlr3.org/download/antlr-3.3-complete.jar" -P "libs"
  - export CLASSPATH="${CLASSPATH}:$(pwd)/libs/*"

script:
  - ./configure --prefix=$HOME/.local
  - time (make all || make all)
  - make check

after_success:
  - export CLASSPATH="${CLASSPATH}:$(pwd)/build/*"
  - java fortran.ofp.FrontEnd tests/f08-tests/R818-F08.f08
  - java fortran.ofp.FrontEnd --verbose tests/f08-tests/R818-F08.f08
