sudo: false
language: java
os: linux
jdk:
  - openjdk7
  - openjdk8
  - oraclejdk8
  - oraclejdk9

install:
  - wget "http://www.antlr3.org/download/antlr-3.3-complete.jar" -P "libs"
  - export CLASSPATH="${CLASSPATH}:$(pwd)/libs/*"

script:
  - ./autoconf.sh
  - ./configure --prefix=$HOME/.local
  - time (make all || make all)
  - make check

after_success:
  - export CLASSPATH="${CLASSPATH}:$(pwd)/build/*"
  - java fortran.ofp.FrontEnd tests/f08-tests/R818-F08.f08
  - java fortran.ofp.FrontEnd --verbose tests/f08-tests/R818-F08.f08

before_deploy:
  - export OFP_VERSION="$(cat make.inc | grep 'OFP_VERSION=' | sed 's/OFP_VERSION=//')"
  - wget https://gist.githubusercontent.com/mbdevpl/cdbc3dab3ae1941870dcaa5bb1b358bc/raw/travis_bintray_descriptor_gen.py
  - python3 travis_bintray_descriptor_gen.py "$OFP_VERSION" "$TRAVIS_OS_NAME-$TRAVIS_JDK_VERSION" "build/*.jar"
  - cat ".bintray.json"

deploy:
  - provider: bintray
    file: ".bintray.json"
    user: "mbdevpl"
    key:
      secure: "ME2CnsB116sxzr5qlVOKh8bP+r4HZPPhPBCehVYy7FYvxi8qPu97wncv5vL+UU6f3Yeov2wLjLDm3Y4+jOiVsqrYRZ7J7pPhxBKDRmpVPmpgO6yBt8E5K8fqsA1k0phZPacOALqcrFS4w9eTM3royv5gNUR2Txq9DFHpzktMN2LRKvjqkQfaoPCLBD32I2T+JI176X82tqJ6BXeG/Ws2+vK6MUjC3KGfj2sAEGnSYKLIh+oepq9OteJmI6qB6wEhlHfAUfa2x98yNOphtziSTuW9PwH0wJ5eLmL+zNJ98zg2+stUpQfEnepYPVKKFGEnljPFGZttpPvt6MLHQYrpDbmbdSh6mlrf+52p0AHVry9Lur+CxnQQqXMhPB52EgDJH2lnDQQmwWdbl1zBTPypZfn/MhJF+SfgfgKW0ls4dHaB2zcxuZ1FC4jvB4C/6YI+gNAEQsOwMNuS5Cy/rfYQHUIqZfjW27i7myDhgIkDP557JrsDt9C1fmAEG2EaWfZ6CrmkrzfElVolbvLQJC+dALgVeh3SEWhubJt5TegEyBhnFuFSyWe/4PHiJXSQaJRYQnwtQ6izBqiD9MLIfcZloyN0snfAxm2dLfnNK9CiIlurFwJ3qbMrh76IR+f2hCk9tj/4tIkLT3Ou6DBf+cRTW9osfaZbvki0XcrqQ/D5Efs="
    on:
      all_branches: true
